const express = require('express')
const router = express.Router()
const AppError = require('../utils/error')
const catchAsync = require('../utils/catchAsync')
const doctor = require('../controllers/doctor')
// const multer = require('multer')
// const { storage } = require('../cloudinary/index')
// const upload = multer({ storage })
// const router = express.Router({ mergeParams: true })

router.get('/doctor', doctor.get)
router.get('/doctor/patients', catchAsync(doctor.getPatientsIndex))
router.get('/doctor/patient/new', doctor.getNewPatient)
router.get('/doctor/secretaries', catchAsync(doctor.getSecretaries))
router.get('/doctor/secretary/new', catchAsync(doctor.getAddSecretary))
router.get('/doctor/secretary/:secretaryId/edit', catchAsync(doctor.getSecretaryEdit))
router.get('/doctor/secretary/:id', catchAsync(doctor.getSecretary))
router.get('/doctor/patient/:id', catchAsync(doctor.getPatient))
router.post('/secretary', catchAsync(doctor.postSecretary))
router.post('/patient', catchAsync(doctor.postPatient))
router.put('/secretary/:id', catchAsync(doctor.putSecretary))
router.put('/patient/:id', catchAsync(doctor.putPatient))
router.delete('/secretary/:id', catchAsync(doctor.deleteSecretary))
router.delete('/patient/:id', catchAsync(doctor.deletePatient))
module.exports = router